// Generated by CoffeeScript 1.6.2
var Image, ImageSchema, ObjectId, Schema, moment, path, string;

string = require("../../../helpers");

path = require("path");

moment = require("moment");

Schema = require("mongoose").Schema;

ObjectId = Schema.Types.ObjectId;

ImageSchema = new Schema({
  _id: ObjectId,
  title: String,
  ts: {
    type: Date,
    "default": Date.now
  },
  unique: String,
  name: String,
  type: String,
  lastModifiedDate: Date,
  path: String,
  size: String,
  published: {
    type: Boolean,
    "default": false
  },
  tags: {
    type: ObjectId,
    ref: "Tag"
  },
  who: {
    type: String,
    ref: "User"
  }
});

Image = module.exports = db.model("Image", ImageSchema);
