// Generated by CoffeeScript 1.6.2
var _images;

_images = module.exports = {
  upload: function(req, res) {
    return res.redirect(req.get("Referer"));
  },
  view: function(req, res) {
    return res.render("pages/images/view", {
      user: req.user,
      nav: req._navObj,
      flash: req.flash("info"),
      que: req.loaded,
      images: req._page,
      prefix: "images"
    });
  },
  edit: function(req, res) {
    return res.render("pages/images/edit", {
      user: req.user,
      nav: req._navObj,
      flash: req.flash("info"),
      que: req.loaded,
      images: req.findOne,
      tags: req._tag,
      prefix: "images"
    });
  }
};
